
"""add_account_aliases

Revision ID: 4a4e7ad4e3cc
Revises: e3bede5bf5e4
Create Date: 2026-09-24 00:09:20.684104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a4e7ad4e3cc'
down_revision = 'e3bede5bf5e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('aliases', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'aliases')
    # ### end Alembic commands ###
