
"""add_split_role

Revision ID: 7ae3b9526d54
Revises: 4a4e7ad4e3cc
Create Date: 2026-09-24 00:41:03.809078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae3b9526d54'
down_revision = '4a4e7ad4e3cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction_splits', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction_splits', 'role')
    # ### end Alembic commands ###
