
"""add_direction_and_dedup_fields

Revision ID: a22785496bd6
Revises: a2897aae34f2
Create Date: 2026-09-11 06:13:35.990620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a22785496bd6'
down_revision = 'a2897aae34f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('direction', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('source_type', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('source_transaction_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('raw_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('canonical_fingerprint', sa.String(), nullable=True))
    op.create_index(op.f('ix_transactions_canonical_fingerprint'), 'transactions', ['canonical_fingerprint'], unique=False)
    op.create_index(op.f('ix_transactions_raw_hash'), 'transactions', ['raw_hash'], unique=False)
    op.create_index(op.f('ix_transactions_source_transaction_id'), 'transactions', ['source_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_source_transaction_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_raw_hash'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_canonical_fingerprint'), table_name='transactions')
    op.drop_column('transactions', 'canonical_fingerprint')
    op.drop_column('transactions', 'raw_hash')
    op.drop_column('transactions', 'source_transaction_id')
    op.drop_column('transactions', 'source_type')
    op.drop_column('transactions', 'direction')
    # ### end Alembic commands ###
