
"""add_import_batch_stats_json

Revision ID: e3bede5bf5e4
Revises: a22785496bd6
Create Date: 2026-09-20 03:10:25.436997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bede5bf5e4'
down_revision = 'a22785496bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import_batches', sa.Column('stats_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('import_batches', 'stats_json')
    # ### end Alembic commands ###
