
"""add_review_duplicate_reasons

Revision ID: f7ee1eaccfa4
Revises: 29980923a6cf
Create Date: 2026-09-10 10:25:40.441737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7ee1eaccfa4'
down_revision = '29980923a6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_id'), 'rules', ['id'], unique=False)
    op.create_table('rule_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_actions_id'), 'rule_actions', ['id'], unique=False)
    op.create_table('rule_conditions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('pattern', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_conditions_id'), 'rule_conditions', ['id'], unique=False)
    op.create_table('export_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('file_sha256', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_records_id'), 'export_records', ['id'], unique=False)
    op.add_column('transactions', sa.Column('description', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('counterparty', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('review_reason', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('duplicate_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'duplicate_reason')
    op.drop_column('transactions', 'review_reason')
    op.drop_column('transactions', 'counterparty')
    op.drop_column('transactions', 'payment_method')
    op.drop_column('transactions', 'description')
    op.drop_index(op.f('ix_export_records_id'), table_name='export_records')
    op.drop_table('export_records')
    op.drop_index(op.f('ix_rule_conditions_id'), table_name='rule_conditions')
    op.drop_table('rule_conditions')
    op.drop_index(op.f('ix_rule_actions_id'), table_name='rule_actions')
    op.drop_table('rule_actions')
    op.drop_index(op.f('ix_rules_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
